# Generated by Django 3.1.2 on 2020-11-02 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_architecture', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realisation',
            name='images',
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(null=True, upload_to='')),
                ('realisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atlas_architecture.realisation')),
            ],
        ),
    ]
