# Generated by Django 3.1.2 on 2020-11-02 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_architecture', '0002_auto_20201102_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
