# Generated by Django 3.1.2 on 2020-11-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_architecture', '0003_auto_20201102_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/realisation'),
        ),
        migrations.AlterField(
            model_name='partenaire',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/partenaire'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/service'),
        ),
    ]
