# Generated by Django 3.1.2 on 2020-11-11 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_architecture', '0005_type_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='code',
        ),
    ]
